### ISSUE TITLE
Add QR Code with more info

### ISSUE THREAD

**Issue by KingBBQ** [KidsLabDe/PicoKrokoBirne#2]
Should we use a link like "Kidslab.de/Glühbirne" or the link to the github project? What do you reckon?

**Comment by KingBBQ** [comment]
![QR-GitHubProjekt](https://user-images.githubusercontent.com/4609107/180185774-e212ff97-c456-475c-9061-319e7a458667.png)

**Comment by strg-v** [comment]
Added the QR-Code to the right of the Pi-Pico. 

![image](https://user-images.githubusercontent.com/61425553/189534550-060652fc-9b00-4287-b57d-c90624f03618.png)
