### ISSUE TITLE
How to solder the NeoPixel?

### ISSUE THREAD

**Issue by KingBBQ** [KidsLabDe/PicoKrokoBirne#3]
4 pins, it's not clear with pin is which...

**Comment by strg-v** [comment]
Added silk screen markings indicated in the [datasheet](https://cdn-shop.adafruit.com/product-files/1138/SK6812+LED+datasheet+.pdf):

![image](https://user-images.githubusercontent.com/61425553/189534933-4590177f-f493-4dcd-9430-e8b3b128dcb5.png)
