### ISSUE TITLE
Add orientation for the Pico

### ISSUE THREAD

**Issue by KingBBQ** [KidsLabDe/PicoKrokoBirne#4]
when soldering the picos to the pcb, 2 times i soldered them with the USB "down". Maybe add a arrow or such, to make the orientation clearer?

**Comment by strg-v** [comment]
Added a box indicating the USB port location, as well as a big arrow pointing upwards ;)

![image](https://user-images.githubusercontent.com/61425553/189534322-6cf7f315-90db-4687-bb66-ed57f527ccf9.png)
