### ISSUE TITLE
Add touch pull up resisitors

### ISSUE THREAD

**Issue by KingBBQ** [KidsLabDe/PicoKrokoBirne#6]
see:
https://github.com/microbit-foundation/microbit-v2-hardware/blob/main/V2/MicroBit_V2.0.0_S_schematic.PDF

for the 4 direction pins

**Comment by strg-v** [comment]
I added four through hole resistor locations for 10MOhm resistors. R1-R4:

![image](https://user-images.githubusercontent.com/61425553/189534242-97e461ed-3f10-4022-b5a7-7d3d221bd339.png)
