### ISSUE TITLE
2nd Servo connector (optional)

### ISSUE THREAD

**Issue by KingBBQ** [KidsLabDe/PicoKrokoBirne#7]
To be able to connect 2 servos at once over the header pins.

**Comment by KingBBQ** [comment]
and please use pins 1-15 for the signal.
PiperMake supports these only in the UI.
<img width="201" alt="Piper Make 2022-07-26 17-27-54" src="https://user-images.githubusercontent.com/4609107/181047347-ff09a78b-d5e1-44a4-b7ce-1ba54f902880.png">
<img width="310" alt="Piper Make 2022-07-26 17-27-46" src="https://user-images.githubusercontent.com/4609107/181047355-b69751cf-46b9-432e-ab43-c2f2a578d342.png">

**Comment by KingBBQ** [comment]
testet the servo connection - works like a charm :)

**Comment by strg-v** [comment]
I added another PWM connector to GPIO10 and moved the existing one to GPIO11.
