### ISSUE TITLE
Which is the right component for grove?

### ISSUE THREAD

**Issue by KingBBQ** [KidsLabDe/PicoKrokoBirne#8]
this one?
https://www.reichelt.de/arduino-grove-universal-buchse-4-pin-90-10er-pack--grv-connec4pin90-p191136.html?PROVID=2788&gclid=EAIaIQobChMI57iek-ib-QIVCZzVCh0nXQ6TEAQYAiABEgICrvD_BwE

**Comment by strg-v** [comment]
I used this one: https://www.mouser.de/ProductDetail/Seeed-Studio/114020163?qs=7MVldsJ5Uaz48D%2F3kIbRqg%3D%3D
